RDKSDatabase/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RDKSDatabase.Models
{
    /// <summary>
    /// TThe Customer class represents the information of the vehicle.
    /// </summary>
    public class Customer
    {
        //The CUS_ID property which is the PK represents the customer ID.
        [Key]
        [Display(Name ="Customer ID")]
        public int CUS_ID { get; set; }

        //The CUS_ACCNUM property represents the customer's account number.
        [Required]
        [StringLength(12)]
        [Display(Name ="Customer Account Number")]
        public string? CUS_ACCNUM { get; set; }

        //The CUS_COMPNAME property represents the customer's company name.
        [Required]
        [StringLength(30)]
        [Display(Name = "Company Name")]
        public string? CUS_COMPNAME { get; set; }

        //The CUS_FNAME property represents the customer's first name.
        [Required]
        [StringLength(20)]
        [Display(Name = "Contact First Name")]
        public string? CUS_FNAME { get; set; }

        //The CUS_LNAME property represents the customer's last name.
        [Required]
        [StringLength(20)]
        [Display(Name = "Contact Last Name")]
        public string? CUS_LNAME { get; set; }

        //The CUS_PHONE property represents the customer's phone number.
        [Required]
        [StringLength(15)]
        [Display(Name = "Contact Phone Number")]
        public string? CUS_PHONE { get; set; }

        //The CUS_ALT_PHONE property represents the customer's alternative phone number.
        [StringLength(15)]
        [Display(Name = "Alternative Phone Number")]
        public string? CUS_ALT_PHONE { get; set; }

        //The CUS_EMAIL property represents the customer's email address.
        [StringLength(30)]
        [Display(Name = "Contact Email")]
        public string? CUS_EMAIL { get; set; }

        //The CUS_ALT_EMAIL property represents the customer's alternative email address.
        [StringLength(30)]
        [Display(Name = "Alt. Email")]
        public string? CUS_ALT_EMAIL { get; set; }

        //The CUS_FR property represents the access to FR facility.
        [Required]
        [Display(Name = "Access to FR")]
        public bool CUS_FR { get; set; }

        //The CUS_TTS property represents the access to TTS facility.
        [Required]
        [Display(Name = "Access to TTS")]
        public bool CUS_TTS { get; set; }

        //The CUS_MEZ property represents the access to Meziadin facility.
        [Required]
        [Display(Name = "Access to MEZ")]
        public bool CUS_MEZ { get; set; }

        //The CUS_DEACTIVATED_COUNT property represents the number of times account deactivated.
        [Required]
        [Display(Name = "Deactivated Count")]
        public int CUS_DEACTIVATED_COUNT { get; set; }

        //The CUS_NOTE property represents the comments, important notes.
        [StringLength(100)]
        [Display(Name = "Notes")]
        public string? CUS_NOTE { get; set; }

        //The Addresses property is a navigation property.
        //The customer entity can be related to any number of Addresses entities.

        //The Permit property is a navigation property.
        //The customer entity can be related to any number of Permit entities.
        public ICollection<Address>? Addresses { get; set; }
        public ICollection<Vehicle>? Vehicles { get; set; }
        public ICollection<Transaction>? Transactions { get; set; }
        public ICollection<Permit>? Permits { get; set; }

    }
}

RDKSDatabase/Controllers/PermitsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RDKSDatabase.Data;
using RDKSDatabase.Models;

namespace RDKSDatabase.Controllers
{
    /// <summary>
    /// This class is the controller for permit model
    /// </summary>
    public class PermitsController : Controller
    {
        private readonly RDKSDatabaseContext _context;

        public PermitsController(RDKSDatabaseContext context)
        {
            _context = context;
        }

        // GET: Permits
        public async Task<IActionResult> Index(string? sortOrder, string? search_prefix, string? search_facility)
        {

            ViewData["SortParm"] = sortOrder == "desc" ? "desc" : "ascending";
            ViewData["prefix"] = search_prefix;
            ViewData["facility"] = search_facility;

            var rDKSDatabaseContext = from permit in _context.Permit select permit;

            System.Diagnostics.Debug.WriteLine(search_prefix != null);
            System.Diagnostics.Debug.WriteLine(search_facility != null);

            if (search_prefix != null)
            {
                rDKSDatabaseContext = rDKSDatabaseContext.Where(p => p.PermitNumberPrefix.ToString().Contains(search_prefix));
            }
            if (search_facility != null)
            {
                rDKSDatabaseContext = rDKSDatabaseContext.Where(p => p.FacilityCode.Contains(search_facility));
            }

            switch (sortOrder)
            {
                case "desc":
                    rDKSDatabaseContext = rDKSDatabaseContext.OrderByDescending(permit => permit.PermitNumberPrefix);
                    break;
                default:
                    rDKSDatabaseContext = rDKSDatabaseContext.OrderBy(permit => permit.PermitNumberPrefix);
                    break;
            }

            return View(await rDKSDatabaseContext.AsNoTracking().ToListAsync());
        }

        // GET: Permits/Details/5
        public async Task<IActionResult> Details(int? prefix, int? id)
        {
            if (id == null || _context.Permit == null)
            {
                return NotFound();
            }

            var permit = await _context.Permit.FindAsync(prefix, id);
     
            if (permit == null)
            {
                return NotFound();
            }

            return View(permit);
        }

        // GET: Permits/Create
        public IActionResult Create()
        {
            ViewData["MaterialCode"] = new SelectList(_context.Set<Material>(), "MaterialCode", "MaterialType");
            return View();
        }

        // POST: Permits/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PermitNumberPrefix,PermitNumber,FacilityCode,PermitApplicationDate,EstimatedVolume,units,EstimatedLoads,Frequency,Comments,ContaminateLoadsDate,ContaminateLoadsComments,ContaminatedLoads,PermitSentToOperatorAndWMF,PermitSavedOnServerAndFiled,HardCopyPermitSavedInFile,ApprovedBy,PermitClosedCardPermissionsRevolked,PermitStatus,PermitType,PermitFee,ExpirationDate,ApplicationFeeInvoiced,ApplicantName,ApplicantPhone,ApplicantEmail,Hauler,Hauler2,CUS_ID,WasteGenerator,MaterialCode")] Permit permit)
        {
            if (ModelState.IsValid)
            {
                _context.Add(permit);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaterialCode"] = new SelectList(_context.Set<Material>(), "MaterialCode", "MaterialType", permit.MaterialCode);
            return View(permit);
        }

        // GET: Permits/Edit/5
        public async Task<IActionResult> Edit(int? prefix, int? id)
        {
            if (id == null || _context.Permit == null)
            {
                return NotFound();
            }

            var permit = await _context.Permit.FindAsync(prefix, id);

            if (permit == null)
            {
                return NotFound();
            }
            ViewData["MaterialCode"] = new SelectList(_context.Set<Material>(), "MaterialCode", "MaterialType", permit.MaterialCode);
            return View(permit);
        }

        // POST: Permits/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int prefix, int id, [Bind("PermitNumberPrefix,PermitNumber,FacilityCode,PermitApplicationDate,EstimatedVolume,units,EstimatedLoads,Frequency,Comments,ContaminateLoadsDate,ContaminateLoadsComments,ContaminatedLoads,PermitSentToOperatorAndWMF,PermitSavedOnServerAndFiled,HardCopyPermitSavedInFile,ApprovedBy,PermitClosedCardPermissionsRevolked,PermitStatus,PermitType,PermitFee,ExpirationDate,ApplicationFeeInvoiced,ApplicantName,ApplicantPhone,ApplicantEmail,Hauler,Hauler2,CUS_ID,WasteGenerator,MaterialCode")] Permit permit)
        {
            if (permit.PermitNumberPrefix != prefix || permit.PermitNumber != id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(permit);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PermitExists(prefix, id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaterialCode"] = new SelectList(_context.Set<Material>(), "MaterialCode", "MaterialType", permit.MaterialCode);
            return View(permit);
        }

        // GET: Permits/Delete/5
        public async Task<IActionResult> Delete(int prefix, int id)
        {
            if (id.Equals(null) || _context.Permit == null)
            {
                return NotFound();
            }

            var permit = await _context.Permit.FindAsync(prefix, id);

            if (permit == null)
            {
                return NotFound();
            }

            return View(permit);
        }

        // POST: Permits/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int prefix, int id)
        {
            if (_context.Permit == null)
            {
                return Problem("Entity set 'RDKSDatabaseContext.Permit'  is null.");
            }
            var permit = await _context.Permit.FindAsync(prefix, id);

            if (permit != null)
            {
                _context.Permit.Remove(permit);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PermitExists(int prefix, int id)
        {
          return (_context.Permit?.Find(prefix, id).Equals(null)).GetValueOrDefault();
        }
    }
}

RDKSDatabase/Controllers/VehiclesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RDKSDatabase.Data;
using RDKSDatabase.Models;

namespace RDKSDatabase.Controllers
{
    public class VehiclesController : Controller
    {
        private readonly RDKSDatabaseContext _context;

        public VehiclesController(RDKSDatabaseContext context)
        {
            _context = context;
        }

        // GET: Vehicles
        public async Task<IActionResult> Index(string searchString1, string searchString2)
        {

            ViewData["CurrentFilter1"] = searchString1;
            ViewData["CurrentFilter2"] = searchString2;

            var vehicle = from v in _context.Vehicle
                          select v;

            if (!String.IsNullOrEmpty(searchString1) && String.IsNullOrEmpty(searchString2))
            {
                vehicle = vehicle.Where(v => v.LICENSE_PLATE.Contains(searchString1));
            }
            if (String.IsNullOrEmpty(searchString1) && !String.IsNullOrEmpty(searchString2))
            {
                vehicle = vehicle.Where(v => v.BADGE.Contains(searchString2));
            }
            if (!String.IsNullOrEmpty(searchString1) && !String.IsNullOrEmpty(searchString2))
            {
                vehicle = vehicle.Where(v => v.LICENSE_PLATE.Contains(searchString1) && v.BADGE.Contains(searchString2));
            }


            return View(await vehicle.AsNoTracking().ToListAsync());
        }

        // GET: Vehicles/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Vehicle == null)
            {
                return NotFound();
            }

            var vehicle = await _context.Vehicle
                .Include(v => v.Customer)
                .FirstOrDefaultAsync(m => m.LICENSE_PLATE == id);
            if (vehicle == null)
            {
                return NotFound();
            }

            return View(vehicle);
        }

        // GET: Vehicles/Create
        public IActionResult Create()
        {
            ViewData["CUS_ID"] = new SelectList(_context.Customer, "CUS_ID", "CUS_FNAME");
            return View();
        }

        // POST: Vehicles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("LICENSE_PLATE,CUS_ID,DESCRIPTION,BADGE,NOTES,NOTES_2")] Vehicle vehicle)
        {
            if (ModelState.IsValid)
            {
                _context.Add(vehicle);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CUS_ID"] = new SelectList(_context.Customer, "CUS_ID", "CUS_FNAME", vehicle.CUS_ID);
            return View(vehicle);
        }

        // GET: Vehicles/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.Vehicle == null)
            {
                return NotFound();
            }

            var vehicle = await _context.Vehicle.FindAsync(id);
            if (vehicle == null)
            {
                return NotFound();
            }
            ViewData["CUS_ID"] = new SelectList(_context.Customer, "CUS_ID", "CUS_FNAME", vehicle.CUS_ID);
            return View(vehicle);
        }

        // POST: Vehicles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("LICENSE_PLATE,CUS_ID,DESCRIPTION,BADGE,NOTES,NOTES_2")] Vehicle vehicle)
        {
            if (id != vehicle.LICENSE_PLATE)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(vehicle);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VehicleExists(vehicle.LICENSE_PLATE))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CUS_ID"] = new SelectList(_context.Customer, "CUS_ID", "CUS_FNAME", vehicle.CUS_ID);
            return View(vehicle);
        }

        // GET: Vehicles/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.Vehicle == null)
            {
                return NotFound();
            }

            var vehicle = await _context.Vehicle
                .Include(v => v.Customer)
                .FirstOrDefaultAsync(m => m.LICENSE_PLATE == id);
            if (vehicle == null)
            {
                return NotFound();
            }

            return View(vehicle);
        }

        // POST: Vehicles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.Vehicle == null)
            {
                return Problem("Entity set 'RDKSDatabaseContext.Vehicle'  is null.");
            }
            var vehicle = await _context.Vehicle.FindAsync(id);
            if (vehicle != null)
            {
                _context.Vehicle.Remove(vehicle);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VehicleExists(string id)
        {
          return (_context.Vehicle?.Any(e => e.LICENSE_PLATE == id)).GetValueOrDefault();
        }
    }
}

RDKSDatabase/Views/Customers/Create.cshtml
@model RDKSDatabase.Models.Customer

@{
    ViewData["Title"] = "Create";
}

<h1>@ViewData["Title"]</h1>

<h4>Customer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CUS_ACCNUM" class="control-label"></label>
                <input asp-for="CUS_ACCNUM" class="form-control" />
                <span asp-validation-for="CUS_ACCNUM" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CUS_COMPNAME" class="control-label"></label>
                <input asp-for="CUS_COMPNAME" class="form-control" />
                <span asp-validation-for="CUS_COMPNAME" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CUS_FNAME" class="control-label"></label>
                <input asp-for="CUS_FNAME" class="form-control" />
                <span asp-validation-for="CUS_FNAME" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CUS_LNAME" class="control-label"></label>
                <input asp-for="CUS_LNAME" class="form-control" />
                <span asp-validation-for="CUS_LNAME" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CUS_PHONE" class="control-label"></label>
                <input asp-for="CUS_PHONE" class="form-control" />
                <span asp-validation-for="CUS_PHONE" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CUS_ALT_PHONE" class="control-label"></label>
                <input asp-for="CUS_ALT_PHONE" class="form-control" />
                <span asp-validation-for="CUS_ALT_PHONE" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CUS_EMAIL" class="control-label"></label>
                <input asp-for="CUS_EMAIL" class="form-control" />
                <span asp-validation-for="CUS_EMAIL" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CUS_ALT_EMAIL" class="control-label"></label>
                <input asp-for="CUS_ALT_EMAIL" class="form-control" />
                <span asp-validation-for="CUS_ALT_EMAIL" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="CUS_FR" /> @Html.DisplayNameFor(model => model.CUS_FR)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="CUS_TTS" /> @Html.DisplayNameFor(model => model.CUS_TTS)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="CUS_MEZ" /> @Html.DisplayNameFor(model => model.CUS_MEZ)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="CUS_DEACTIVATED_COUNT" class="control-label"></label>
                <input asp-for="CUS_DEACTIVATED_COUNT" class="form-control" />
                <span asp-validation-for="CUS_DEACTIVATED_COUNT" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CUS_NOTE" class="control-label"></label>
                <input asp-for="CUS_NOTE" class="form-control" />
                <span asp-validation-for="CUS_NOTE" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RDKSDatabase/Views/Customers/InfoPage.cshtml
@model RDKSDatabase.ViewModels.CustomerInfo
@using RDKSDatabase.Models;

@{
    ViewData["Title"] = "Customer Related Info";
}

<h1>@ViewData["Title"]</h1>

<h4>Customer Info</h4>

<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.SelectedCustomer.CUS_ACCNUM)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SelectedCustomer.CUS_COMPNAME)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SelectedCustomer.CUS_FNAME)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SelectedCustomer.CUS_LNAME)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SelectedCustomer.CUS_PHONE)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SelectedCustomer.CUS_EMAIL)
        </th>
        <th></th>
    </tr>
    </thead>
    @{
        int cus_id = Model.SelectedCustomer.CUS_ID;
    }

    <tbody>
        <tr>
            <td>
                @Html.DisplayFor(modelItem => modelItem.SelectedCustomer.CUS_ACCNUM)
            </td>
            <td>
                @Html.DisplayFor(modelItem => modelItem.SelectedCustomer.CUS_COMPNAME)
            </td>
            <td>
                @Html.DisplayFor(modelItem => modelItem.SelectedCustomer.CUS_FNAME)
            </td>
            <td>
                @Html.DisplayFor(modelItem => modelItem.SelectedCustomer.CUS_LNAME)
            </td>
            <td>
                @Html.DisplayFor(modelItem => modelItem.SelectedCustomer.CUS_PHONE)
            </td>
            <td>
                @Html.DisplayFor(modelItem => modelItem.SelectedCustomer.CUS_EMAIL)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@cus_id">Edit</a> |
                <a asp-action="Details" asp-route-id="@cus_id">Details</a> |
                <a asp-action="Delete" asp-route-id="@cus_id">Delete</a>
            </td>
        </tr>
    </tbody>
</table>

<h4>Address Info</h4>

@if (Model.Addresses.Any())
{
    Address address = Model.Addresses.First();
    <table class="table">
        <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => address.ADDR_STREET)
            </th>
            <th>
                @Html.DisplayNameFor(model => address.ADDR_CITY)
            </th>
            <th>
                @Html.DisplayNameFor(model => address.ADDR_PROV)
            </th>
            <th>
                @Html.DisplayNameFor(model => address.ADDR_POCODE)
            </th>
            <th></th>
        </tr>
        </thead>

        <tbody>
            @foreach (var item in Model.Addresses) {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ADDR_STREET)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ADDR_CITY)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ADDR_PROV)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ADDR_POCODE)
                    </td>
                    <td>
                        <a asp-controller="Addresses" asp-action="Edit" asp-route-id="@item.ADDR_ID">Edit</a> |
                        <a asp-controller="Addresses" asp-action="Details" asp-route-id="@item.ADDR_ID">Details</a> |
                        <a asp-controller="Addresses" asp-action="Delete" asp-route-id="@item.ADDR_ID">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
} 
else
{
    <p>
        No Records Found!
    </p>
}

<h4>Permit Info</h4>

@if (Model.Permits.Any())
{
    Permit permit = Model.Permits.First();
    <table class="table">
        <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => permit.PermitNumberPrefix)
            </th>
            <th>
                @Html.DisplayNameFor(model => permit.PermitNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => permit.ApplicantName)
            </th>
            <th>
                @Html.DisplayNameFor(model => permit.ApplicantPhone)
            </th>
            <th>
                @Html.DisplayNameFor(model => permit.ApplicantEmail)
            </th>
            <th>
                @Html.DisplayNameFor(model => permit.ExpirationDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => permit.FacilityCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => permit.Frequency)
            </th>
            <th>
                @Html.DisplayNameFor(model => permit.PermitApplicationDate)
            </th>
            <th></th>
        </tr>
        </thead>

        <tbody>
            @foreach (var item in Model.Permits) {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.PermitNumberPrefix)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PermitNumber)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ApplicantName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ApplicantPhone)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ApplicantEmail)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FacilityCode)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Frequency)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PermitApplicationDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ExpirationDate)
                    </td>
                    <td>
                        <a asp-controller="Permits" asp-action="Edit" asp-route-prefix="@item.PermitNumberPrefix" asp-route-id="@item.PermitNumber">Edit</a> |
                        <a asp-controller="Permits" asp-action="Details" asp-route-prefix="@item.PermitNumberPrefix" asp-route-id="@item.PermitNumber">Details</a> |
                        <a asp-controller="Permits" asp-action="Delete" asp-route-prefix="@item.PermitNumberPrefix" asp-route-id="@item.PermitNumber">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
} 
else
{
    <p>
        No Records Found!
    </p>
}

<h4>Vehicle Info</h4>

@if (Model.Vehicles.Any())
{
    Vehicle vehicle = Model.Vehicles.First();
    <table class="table">
        <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => vehicle.LICENSE_PLATE)
            </th>
            <th>
                @Html.DisplayNameFor(model => vehicle.DESCRIPTION)
            </th>
            <th>
                @Html.DisplayNameFor(model => vehicle.BADGE)
            </th>
            <th>
                @Html.DisplayNameFor(model => vehicle.NOTES)
            </th>
            <th></th>
        </tr>
        </thead>

        <tbody>
            @foreach (var item in Model.Vehicles) {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.LICENSE_PLATE)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DESCRIPTION)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.BADGE)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NOTES)
                    </td>
                    <td>
                        <a asp-controller="Vehicles" asp-action="Edit" asp-route-id="@item.LICENSE_PLATE">Edit</a> |
                        <a asp-controller="Vehicles" asp-action="Details" asp-route-id="@item.LICENSE_PLATE">Details</a> |
                        <a asp-controller="Vehicles" asp-action="Delete" asp-route-id="@item.LICENSE_PLATE">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
} 
else
{
    <p>
        No Records Found!
    </p>
}
<form asp-action="Index" method="get">
    <input type="submit" value="Back to full list" class="btn btn-default" style="background: lightblue"/>
</form> 